"""
run_cross_synthetic_lora_transfer.py

Cross-dataset transfer evaluation for a single merged model checkpoint, where
each "dataset" is a synthetic task batch generated by
inspect/generate_synthetic.py.

Evaluates:
  - Base TabPFN
  - Base sampling + tuned belief (merged_model_state)

Metrics:
  - Accuracy / NLL / ECE on fixed synthetic anchors
  - EMD (strict fixed-anchor path)
  - Belief drift visualization grids
"""

"""
python run_cross_synthetic_lora_transfer.py \
  --model-path /home/boreum/project/tabpfn-scloss/synthetic_model/merged_model_state_generated_train_800_seed42_20260319_221040.pt \
  --dataset-seeds 44 \
  --no-include-base 

"""

import argparse
import csv
import os
from dataclasses import dataclass
from typing import Any, Optional

import jax
import numpy as np
import torch

from predictive_rule import ClassifierPredRule
from run_classification import (
    _evaluate_basic_on_fixed_synthetic_anchors,
    generate_synthetic_task_dataset,
)
from run_cross_dataset_lora_transfer import (
    _slugify,
    parse_int_tuple,
)
from run_saved_model_rollout_compare import _run_fixed_queries_rollout_grid_analysis
from eval import (
    build_fixed_synthetic_anchor_suite,
    _compute_fixed_anchor_suite_eval_for_model_pair,
)


@dataclass(frozen=True)
class SyntheticDatasetSpec:
    seed: int
    n_tasks: Optional[int] = None
    emd_context_size: Optional[int] = None
    rollout_base_n: Optional[int] = None


def _build_synthetic_dataset_specs(
    dataset_seeds: tuple[int, ...],
    n_tasks_per_dataset: int,
) -> tuple[SyntheticDatasetSpec, ...]:
    return tuple(
        SyntheticDatasetSpec(seed=int(s), n_tasks=int(n_tasks_per_dataset))
        for s in dataset_seeds
    )


def _fit_rule_for_anchor(
    *,
    categorical_x: list[bool],
    n_estimators: int,
    x_ctx: np.ndarray,
    y_ctx_local: np.ndarray,
    locked_state: Optional[dict[str, torch.Tensor]] = None,
) -> ClassifierPredRule:
    rule = ClassifierPredRule(categorical_x, n_estimators=n_estimators)
    if locked_state is not None:
        rule._locked_state_dict = {
            k: v.clone().cpu() for k, v in locked_state.items()
        }
    rule.fit(x_ctx, y_ctx_local)
    return rule


def _load_locked_state(path: str) -> dict[str, torch.Tensor]:
    ckpt = torch.load(path, map_location="cpu")
    if isinstance(ckpt, dict) and "state_dict" in ckpt and isinstance(ckpt["state_dict"], dict):
        raw = ckpt["state_dict"]
    elif isinstance(ckpt, dict) and all(torch.is_tensor(v) for v in ckpt.values()):
        raw = ckpt
    else:
        raise ValueError(
            f"Unsupported checkpoint format at {path}. "
            "Expected merged checkpoint with 'state_dict' or raw state_dict."
        )
    out: dict[str, torch.Tensor] = {}
    for k, v in raw.items():
        if torch.is_tensor(v):
            out[str(k)] = v.detach().cpu().clone()
    if len(out) == 0:
        raise ValueError(f"No tensor state entries found in checkpoint: {path}")
    return out


def _select_drift_task_index(*, n_tasks: int, requested_index: int, seed: int) -> int:
    if n_tasks <= 0:
        raise ValueError("Synthetic dataset has no tasks.")
    if requested_index >= 0:
        return int(np.clip(requested_index, 0, n_tasks - 1))
    rng = np.random.default_rng(int(seed))
    return int(rng.integers(0, n_tasks))


def _build_drift_pools_for_task(
    *,
    x_tasks: np.ndarray,
    y_tasks: np.ndarray,
    task_index: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    x_task = np.asarray(x_tasks[int(task_index)], dtype=np.float32)
    y_task_global = np.asarray(y_tasks[int(task_index)]).astype(np.int64)
    class_ids, y_task_local = np.unique(y_task_global, return_inverse=True)
    y_task = np.asarray(y_task_local, dtype=np.int64)
    class_ids = np.asarray(class_ids, dtype=np.int64)
    class_names = np.asarray([str(int(c)) for c in class_ids])
    return x_task, y_task, x_task, x_task, class_names


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model-path",
        type=str,
        required=True,
        help="Path to merged model checkpoint to evaluate directly.",
    )
    parser.add_argument("--n-estimators", type=int, default=1)
    parser.add_argument(
        "--include-base",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Evaluate the plain base TabPFN variant as well (default: enabled).",
    )
    parser.add_argument("--out-dir", type=str, default="cross_synthetic_transfer")
    parser.add_argument("--save-csv", action="store_true")

    parser.add_argument(
        "--dataset-seeds",
        type=str,
        default="101",
        help="Comma-separated seeds defining synthetic evaluation datasets.",
    )
    parser.add_argument(
        "--synthetic-eval-tasks",
        type=int,
        default=10,
        help="Number of tasks to generate per synthetic evaluation dataset.",
    )
    parser.add_argument(
        "--synthetic-split-prefix",
        type=str,
        default="cross_eval",
        help="Split-name prefix passed into the synthetic generator.",
    )

    # EMD settings (strict fixed-anchor)
    parser.add_argument(
        "--enable-emd",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Enable strict fixed-anchor EMD evaluation (default: enabled).",
    )
    parser.add_argument("--emd-anchor-count", type=int, default=3)
    parser.add_argument("--emd-context-size", type=int, default=100)
    parser.add_argument("--emd-query-pool-size", type=int, default=20)
    parser.add_argument("--emd-queries-per-anchor", type=int, default=4)
    parser.add_argument("--emd-prefix-depths", type=str, default="0,2,4")
    parser.add_argument("--emd-k-values", type=str, default="3,7,11,15")
    parser.add_argument("--emd-continuation-depth", type=int, default=30)
    parser.add_argument("--emd-n-continuations", type=int, default=8)
    parser.add_argument(
        "--emd-fixed-rollout-paths",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Use fixed rollout keys in EMD suite (default: enabled).",
    )

    # Belief drift visualization settings
    parser.add_argument(
        "--enable-drift-plot",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Enable fixed-query belief drift grid plots (default: disabled).",
    )
    parser.add_argument("--drift-task-index", type=int, default=0)
    parser.add_argument("--rollout-n-queries", type=int, default=6)
    parser.add_argument("--rollout-grid-rows", type=int, default=2)
    parser.add_argument("--rollout-grid-cols", type=int, default=3)
    parser.add_argument("--rollout-base-n", type=int, default=100)
    parser.add_argument("--rollout-depth", type=int, default=20)
    parser.add_argument("--rollout-n-paths", type=int, default=8)
    args = parser.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)

    dataset_seeds = parse_int_tuple(args.dataset_seeds)
    dataset_specs = _build_synthetic_dataset_specs(
        dataset_seeds=dataset_seeds,
        n_tasks_per_dataset=int(args.synthetic_eval_tasks),
    )
    emd_prefix_depths = parse_int_tuple(args.emd_prefix_depths)
    emd_k_values = parse_int_tuple(args.emd_k_values)
    model_path = os.path.abspath(args.model_path)
    if not os.path.isfile(model_path):
        raise FileNotFoundError(f"Merged model file not found: {model_path}")
    merged_model_state = _load_locked_state(model_path)
    print(f"Loaded merged model: {model_path}")

    print(
        "Run options: "
        f"EMD={'on' if args.enable_emd else 'off'}, "
        f"drift_plot={'on' if args.enable_drift_plot else 'off'}, "
        f"fixed_emd_rollout_keys={'on' if args.emd_fixed_rollout_paths else 'off'}"
    )

    all_rows: list[dict[str, Any]] = []

    for ds_idx, spec in enumerate(dataset_specs):
        print("\n" + "=" * 80)
        print(f"SYNTHETIC DATASET {ds_idx} (seed={spec.seed})")
        print("=" * 80)

        split_name = f"{args.synthetic_split_prefix}_{ds_idx}"
        n_tasks = int(spec.n_tasks) if spec.n_tasks is not None else int(args.synthetic_eval_tasks)
        x_tasks, y_tasks, categorical_x, dataset_name = generate_synthetic_task_dataset(
            n_tasks=n_tasks,
            seed=int(spec.seed),
            split_name=split_name,
        )
        global_num_classes = int(np.max(y_tasks)) + 1
        dataset_tag = _slugify(dataset_name)
        ds_dir = os.path.join(args.out_dir, dataset_tag)
        os.makedirs(ds_dir, exist_ok=True)
        ds_emd_context_size = (
            int(spec.emd_context_size)
            if spec.emd_context_size is not None
            else int(args.emd_context_size)
        )
        ds_rollout_base_n = (
            int(spec.rollout_base_n)
            if spec.rollout_base_n is not None
            else int(args.rollout_base_n)
        )
        print(
            f"  name={dataset_name}, tasks={x_tasks.shape[0]}, points/task={x_tasks.shape[1]}, "
            f"dim={x_tasks.shape[2]}, classes={global_num_classes}, "
            f"emd_context_size={ds_emd_context_size}, rollout_base_n={ds_rollout_base_n}"
        )

        key_emd = jax.random.PRNGKey(int(spec.seed))
        emd_suite = build_fixed_synthetic_anchor_suite(
            key=key_emd,
            x_tasks=np.asarray(x_tasks, dtype=np.float32),
            y_tasks=np.asarray(y_tasks).astype(np.int64),
            anchor_count=int(args.emd_anchor_count),
            context_size=ds_emd_context_size,
            query_pool_size=int(args.emd_query_pool_size),
            queries_per_anchor=int(args.emd_queries_per_anchor),
            prefix_depths=emd_prefix_depths,
            fixed_rollout_paths=bool(args.emd_fixed_rollout_paths),
        )
        (
            anchor_contexts,
            _anchor_contexts_global,
            anchor_context_class_ids,
            anchor_query_banks_x,
            anchor_query_banks_y,
            anchor_rollout_pools,
            fixed_rollout_keys,
            _,
        ) = emd_suite

        rollout_query_indices = None
        drift_x_ctx_pool = drift_y_ctx_pool = drift_x_query_pool = drift_x_sampling_pool = None
        drift_class_names = None
        if args.enable_drift_plot:
            drift_task_index = _select_drift_task_index(
                n_tasks=int(x_tasks.shape[0]),
                requested_index=int(args.drift_task_index),
                seed=int(spec.seed),
            )
            (
                drift_x_ctx_pool,
                drift_y_ctx_pool,
                drift_x_query_pool,
                drift_x_sampling_pool,
                drift_class_names,
            ) = _build_drift_pools_for_task(
                x_tasks=x_tasks,
                y_tasks=y_tasks,
                task_index=drift_task_index,
            )
            rng = np.random.default_rng(int(spec.seed))
            replace = len(drift_x_query_pool) < int(args.rollout_n_queries)
            rollout_query_indices = np.asarray(
                rng.choice(
                    len(drift_x_query_pool),
                    size=int(args.rollout_n_queries),
                    replace=replace,
                ),
                dtype=int,
            )
            print(
                f"  drift task={drift_task_index}, "
                f"fixed rollout queries={rollout_query_indices.tolist()}"
            )

        variants: list[tuple[str, Optional[dict[str, torch.Tensor]]]] = []
        if args.include_base:
            variants.append(("base", None))
        variants.append(("model", merged_model_state))

        for variant_name, variant_locked_state in variants:
            if args.enable_emd:
                emd_mean, emd_std, emd_cov, acc, nll, ece, _ = _compute_fixed_anchor_suite_eval_for_model_pair(
                    key=jax.random.PRNGKey(0),
                    categorical_x=categorical_x,
                    n_estimators=args.n_estimators,
                    sampling_model_state_dict=None,
                    belief_model_state_dict=variant_locked_state,
                    anchor_contexts=anchor_contexts,
                    anchor_context_class_ids=anchor_context_class_ids,
                    anchor_query_banks_x=anchor_query_banks_x,
                    anchor_query_banks_y=anchor_query_banks_y,
                    global_num_classes=global_num_classes,
                    prefix_depths=emd_prefix_depths,
                    k_values=emd_k_values,
                    continuation_depth=int(args.emd_continuation_depth),
                    n_continuations=int(args.emd_n_continuations),
                    fixed_rollout_keys=fixed_rollout_keys,
                    anchor_rollout_pools=anchor_rollout_pools,
                )
                metrics = {
                    "accuracy_mean": float(acc),
                    "nll_mean": float(nll),
                    "ece_mean": float(ece),
                    "n_anchors": float(len(anchor_contexts)),
                }
            else:
                pred_rule = ClassifierPredRule(categorical_x, n_estimators=args.n_estimators)
                if variant_locked_state is not None:
                    pred_rule._locked_state_dict = {
                        k: v.clone().cpu() for k, v in variant_locked_state.items()
                    }
                metrics = _evaluate_basic_on_fixed_synthetic_anchors(
                    pred_rule=pred_rule,
                    anchor_contexts=anchor_contexts,
                    anchor_context_class_ids=anchor_context_class_ids,
                    anchor_query_banks_x=anchor_query_banks_x,
                    anchor_query_banks_y=anchor_query_banks_y,
                    global_num_classes=global_num_classes,
                )
                emd_mean = float("nan")
                emd_std = float("nan")
                emd_cov = -1

            print(
                f"  [{variant_name}] "
                f"acc={metrics['accuracy_mean']:.4f}, "
                f"nll={metrics['nll_mean']:.4f}, "
                f"ece={metrics['ece_mean']:.4f}, "
                f"emd={emd_mean:.6f}, emd_std={emd_std:.6f}, cov={emd_cov}"
            )

            if args.enable_drift_plot and rollout_query_indices is not None:
                drift_x_ctx = np.asarray(anchor_contexts[0][0], dtype=np.float32)
                drift_y_ctx = np.asarray(anchor_contexts[0][1]).astype(np.int64)
                drift_rule = _fit_rule_for_anchor(
                    categorical_x=categorical_x,
                    n_estimators=args.n_estimators,
                    x_ctx=drift_x_ctx,
                    y_ctx_local=drift_y_ctx,
                    locked_state=variant_locked_state,
                )
                tag = f"{dataset_tag}_{variant_name}"
                res = _run_fixed_queries_rollout_grid_analysis(
                    x_context_pool=np.asarray(drift_x_ctx_pool, dtype=np.float32),
                    y_context_pool=np.asarray(drift_y_ctx_pool).astype(np.int64),
                    x_query_pool=np.asarray(drift_x_query_pool, dtype=np.float32),
                    x_sampling_pool=np.asarray(drift_x_sampling_pool, dtype=np.float32),
                    query_indices=rollout_query_indices.tolist(),
                    class_names=drift_class_names,
                    pred_rule_factory=lambda pr=drift_rule: pr,
                    base_n=ds_rollout_base_n,
                    depth=int(args.rollout_depth),
                    n_paths=int(args.rollout_n_paths),
                    seed=int(spec.seed),
                    n_rows=int(args.rollout_grid_rows),
                    n_cols=int(args.rollout_grid_cols),
                    save_dir=ds_dir,
                    tag=tag,
                    show=False,
                )
                src = res["paths"]["grid_plot_png"]
                dst = os.path.join(ds_dir, f"belief_{tag}.png")
                if os.path.abspath(src) != os.path.abspath(dst):
                    os.replace(src, dst)

            row = {
                "dataset_index": int(ds_idx),
                "dataset_seed": int(spec.seed),
                "dataset_name": dataset_name,
                "variant": variant_name,
                "n_tasks": int(x_tasks.shape[0]),
                "points_per_task": int(x_tasks.shape[1]),
                "n_features": int(x_tasks.shape[2]),
                "n_classes": int(global_num_classes),
                "accuracy": float(metrics["accuracy_mean"]),
                "nll": float(metrics["nll_mean"]),
                "ece": float(metrics["ece_mean"]),
                "n_anchors": int(metrics["n_anchors"]),
                "emd_mean": float(emd_mean),
                "emd_std": float(emd_std),
                "emd_coverage": int(emd_cov),
            }
            all_rows.append(row)

        if args.save_csv:
            csv_path = os.path.join(ds_dir, f"transfer_metrics_{dataset_tag}.csv")
            with open(csv_path, "w", newline="", encoding="utf-8") as f:
                w = csv.DictWriter(f, fieldnames=list(all_rows[-len(variants):][0].keys()))
                w.writeheader()
                for row in all_rows[-len(variants):]:
                    w.writerow(row)
            print(f"  saved: {csv_path}")

    if args.save_csv and len(all_rows) > 0:
        out_csv = os.path.join(args.out_dir, "transfer_metrics_all.csv")
        with open(out_csv, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=list(all_rows[0].keys()))
            w.writeheader()
            for row in all_rows:
                w.writerow(row)
        print(f"\nSaved aggregate CSV: {out_csv}")


if __name__ == "__main__":
    main()
